default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: nick

development:
  <<: *default
  database: debugging_development

test:
  <<: *default
  database: debugging_test

production:
  <<: *default
  database: debugging_production
